### ISSUE TITLE
Namespacing templates

### ISSUE THREAD

**Issue by shilov** [wbyoung/gulp-ember-emblem#1]
@wbyoung what is the proper approach for namespacing so that templates with the same filename don't conflict?

For ex, `templates/foo/index` and `templates/bar/index`

**Comment by wbyoung** [comment]
There's an example on [gulp-define-module's documentation](https://github.com/wbyoung/gulp-define-module#optionscontext), but here it is modified for Ember and Emblem:

``` javascript
defineModule('plain', {
  wrapper: '(Ember.TEMPLATES[\'<%= templateName %>\'] = <%= emberHandlebars %>)',
  context: function(context) {
    var file = context.file;
    var name = path.relative(file.cwd, file.path)
      .slice(0, -path.extname(file.path).length)
      .split(path.sep).join('.');
    return { templateName: name };
  }
})
```

Another way is to define all of your templates in one directory and name them `foo.index.hbs`, `bar.index.hbs`.

Please let me know if you have any issues with that.
